# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'CAFS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CAFS
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  
end
